### ISSUE TITLE
希望像RssBud一样加入过滤信息功能

### ISSUE THREAD

**Issue by kingswon** [easychen/rsspush#1]
另外Sendkey是不是可以保存下来，不用每次添加时都需要重新填写Sendkey

![IMG_6863](https://user-images.githubusercontent.com/24834857/188555494-5a53d611-76ff-4a80-99f6-19134e5946d7.png)

**Comment by easychen** [comment]
没用过RssBud，能详细说下这个信息过滤是啥吗？允许设置关键字，然后在标题中匹配到后推送通知？

**Comment by kingswon** [comment]
> 

![IMG_6883](https://user-images.githubusercontent.com/24834857/188636474-e3e86877-681a-43fa-abf3-1973b6f848e5.jpeg)
可以使用正则表达式匹配 保留或者去掉匹配到的标题或者描述等等

**Comment by easychen** [comment]
最新版镜像加了匹配关键字。正则表达式的话，对于普通用户来讲太复杂了就不加了。

**Comment by Felmon** [comment]
> 最新版镜像加了匹配关键字。正则表达式的话，对于普通用户来讲太复杂了就不加了。

关键字可以多个匹配吗？ 支持正则最好了，都会安装docker了也不算普通用户了吧
