### ISSUE TITLE
少数派RSS，重复更新推送

### ISSUE THREAD

**Issue by Beurling** [easychen/rsspush#10]
添加RSS源后最开始几次运行正常，但之后会随机卡在一条推送上后，反复推送相同的内容，查看data文件夹，发现json中 last_content没有对应更新，估计是导致重复推送的原因，求解决方案

重装docker后还是会遇到这个问题

**Comment by easychen** [comment]
盲猜了一下，可能是因为通知部分超时导致该次监测数据没有保存，最新版镜像（ "2022.09.16.13.53+" ）修改了保存逻辑，每次监测到先保存再发通知，可以更新镜像试试。

**Comment by Beurling** [comment]
> 盲猜了一下，可能是因为通知部分超时导致该次监测数据没有保存，最新版镜像（ "2022.09.16.13.53+" ）修改了保存逻辑，每次监测到先保存再发通知，可以更新镜像试试。

好的，马上试一下，谢谢😀

**Comment by Beurling** [comment]
完美运行两天，没有重复推送 😊
