### ISSUE TITLE
使用环境变量HTTP_PROXY后，无法连接http://rsshub:1200

### ISSUE THREAD

**Issue by ZGLinus** [easychen/rsspush#20]
使用 `HTTP_PROXY` 后，添加 `http://rsshub:1200` 的任务后返回 `{"result":false}`， 但是，在容器内使用 `curl` 又会获得正常的rss内容。如果使用主机 IP 加端口的方法访问rsshub，又会恢复正常。
移除 `HTTP_PROXY` 重建容器也会恢复正常。
`rsspush` 和 `rsshub` 容器都处在我自建的网桥下，两个容器可以相互访问。

**Comment by easychen** [comment]
HTTP_PROXY 只对 RSSPush 的抓取操作（fetch函数）生效。因此添加 PROXY 后不能fetch内部容器是正常的。容器内curl 不走 fetch，所以能访问其他容器。

你要用rsshub，就把代理直接加到rsshub上就行了，没必要在 rsspush 上加。

**Comment by ZGLinus** [comment]
我想你误会了，我用的rss链接有一部分是来自 rsshub 容器的，另外一部分来自外网，这其中有一些需要走代理才能稳定连接。
