### ISSUE TITLE
建议直接取消其他接口吧  反正只有你的付费什么酱才能用 浪费大家时间  

### ISSUE THREAD

**Issue by AIEOV** [easychen/rsspush#25]

**Comment by AIEOV** [comment]
或者填写webhook  也是收不到

**Comment by AIEOV** [comment]
测试

**Comment by easychen** [comment]
apprise 为什么发不出来自己去读它的文档啊，总不能我还要支持appires吧？
不要把自己的能力不行归咎给开源项目啊…

**Comment by easychen** [comment]
① 我们发布镜像时，AppRise 是可用的。
② 这是一个免费产品，请自行阅读 rsspush 的文档、apprise 的文档、自行定位和调试你遇到的问题。
③ 我们并不提供免费客服，尤其是对不会好好说的的用户。
