### ISSUE TITLE
希望大佬支持Gotify推送服务

### ISSUE THREAD

**Issue by spysir** [easychen/rsspush#3]
Gotify:免费开源，可自建服务器，支持android, windows, chrome,有自己的WEB端，可能是android 端最好的通知推送服务方案

**Comment by easychen** [comment]
用webhook（+Hiflow）可以自己实现吧

**Comment by spysir** [comment]
> 用webhook（+Hiflow）可以自己实现吧

如果能直接支持Gotify会更方便，这样对小白更友好一些

**Comment by easychen** [comment]
> > 用webhook（+Hiflow）可以自己实现吧
> 
> 如果能直接支持Gotify会更方便，这样对小白更友好一些

新版本添加了对 Apprise 的支持，可以推送包括 Gotify 在内的上百的通道。请参考文档使用 https://github.com/easychen/rsspush#%E9%80%9A%E8%BF%87-apprise-%E6%8E%A8%E9%80%81%E6%9B%B4%E6%96%B0
