### ISSUE TITLE
大佬请问可以把文章的标题一块推送出来吗？目前的title字段的值是 “任务title ” + “更新了”，不是文章的标题

### ISSUE THREAD

**Issue by niuyi1017** [easychen/rsspush#4]
![微信截图_20220912111325](https://user-images.githubusercontent.com/30387148/189567330-95b846d6-4fae-47dc-a848-1c17a23bb6b0.png)

**Comment by easychen** [comment]
这里是手误，已经调整了。正在打包镜像，应该半个小时后就更新了。可以重新pull下试试。
