### ISSUE TITLE
无论怎么修改环境变量，RSSHub Feed生成助手里的地址都还是默认的那个

### ISSUE THREAD

**Issue by raining1123** [easychen/rsspush#7]
![image](https://user-images.githubusercontent.com/17892238/190053412-5776da4d-b033-4e80-9024-55bceadd3873.png)
![image](https://user-images.githubusercontent.com/17892238/190053415-6970388d-14ed-49dc-92af-ca4983e76e49.png)

**Comment by easychen** [comment]
看起来 RSS_BASE 之间没有下划线？

**Comment by easychen** [comment]
感谢反馈。我查了下，这的确是一个bug。不过因为不太影响使用，等下次打包rsspush时一起修正吧。

**Comment by easychen** [comment]
> 感谢反馈。我查了下，这的确是一个bug。不过因为不太影响使用，等下次打包rsspush时一起修正吧。

镜像 2022.09.15.13.30+  已经修复该问题，可以再试试。
