### ISSUE TITLE
测试时一直提示解析失败{"result":false}

### ISSUE THREAD

**Issue by Juijote** [easychen/rsspush#8]
自部署的rsshub地址是可以正常使用,是不是跟我rsshub的网址用了https有关?
可是我也试过用本地部署方式,还是解析失败.
rsshub已经是把路由更到最新的了.

**Comment by easychen** [comment]
rsshub官网的URL经常因为反爬而不可用。本地的rsshub初次抓取某一个内容时经常超时失败，要多次请求后才会成功。

这些都和rsshub相关，直接使用rss feed地址很少出现类似错误，建议换用其他feed进行测试。
