### ISSUE TITLE
关于返回内容的问题

### ISSUE THREAD

**Issue by JulyFinal** [easychen/rsspush#9]
尊敬的开发者

你好，

我这边采用了apprise  mailto来推送消息，返回的邮件内容是markdown格式的，邮箱无法解析。

请问这个格式是经由push决定的还是apprise呢？

**Comment by easychen** [comment]
> 尊敬的开发者
> 
> 你好，
> 
> 我这边采用了apprise mailto来推送消息，返回的邮件内容是markdown格式的，邮箱无法解析。
> 
> 请问这个格式是经由push决定的还是apprise呢？

这是默认的。我稍后看看不要加个参数来指定下。

**Comment by easychen** [comment]
镜像 2022.09.15.13.30+  新增 apprise:raw 命令，用于推送原始 RSS 内容。

https://github.com/easychen/rsspush#%E9%80%9A%E8%BF%87-apprise-%E6%8E%A8%E9%80%81%E6%9B%B4%E6%96%B0

**Comment by JulyFinal** [comment]
> > 尊敬的开发者
> > 你好，
> > 我这边采用了apprise mailto来推送消息，返回的邮件内容是markdown格式的，邮箱无法解析。
> > 请问这个格式是经由push决定的还是apprise呢？
> 
> 这是默认的。我稍后看看不要加个参数来指定下。

谢谢！这么快就更新。

我这边收到的邮件也由markdown变换为html了，但是这次的内容展示为text格式的html并没有进行渲染。

![问题1](https://user-images.githubusercontent.com/14924875/190532538-1e35fe7e-18ac-409e-9917-5c085ffef94b.png)

看起来似乎是内容不全导致的无法渲染。

我自己写了一个标签完整的邮件，通过apprise发送结果是对的

![正常1](https://user-images.githubusercontent.com/14924875/190532797-ffdf402f-29b8-492b-8e92-b136c6c197c4.png)

能否麻烦开发者能否看一下 是否是RSS发送邮件的时候内容不全导致的。 谢谢！

**Comment by easychen** [comment]
首先 HTML 不完整的问题应该是双引号未转义导致的，已经在镜像 "2022.09.16.02.58+" 修复。

然后完整的 HTML 不渲染是因为没有给 apprise 指定输入内容格式。需要写成 

```
apprise:raw -i html mailto://....
```

**Comment by JulyFinal** [comment]
> 首先 HTML 不完整的问题应该是双引号未转义导致的，已经在镜像 "2022.09.16.02.58+" 修复。
> 
> 然后完整的 HTML 不渲染是因为没有给 apprise 指定输入内容格式。需要写成
> 
> ```
> apprise:raw -i html mailto://....
> ```

好的，辛苦修复，感谢！

**Comment by JulyFinal** [comment]
@easychen  

请问开发者，接下来还有其他的功能增加吗？

如果有的话希望能参考一下我的需求：

1. 修改订阅的标题和发送邮件的的标题
2. 获取全文RSS（利用Mercury Parser）
3. 针对每个RSS加入PROXY

谢谢

**Comment by easychen** [comment]
RSSPush 的定位是通知器而不是阅读工具，因此不会做。不过你可以通过 webhook 接入 HiFlow 之类的场景连接器，在里边自行处理。 

Proxy的话，我记得RSSHub本身就支持，可以用它中转下。

**Comment by JulyFinal** [comment]
> RSSPush 的定位是通知器而不是阅读工具，因此不会做。不过你可以通过 webhook 接入 HiFlow 之类的场景连接器，在里边自行处理。
> 
> Proxy的话，我记得RSSHub本身就支持，可以用它中转下。

好的 感谢
